apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 552.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '10'
    run.googleapis.com/operation-id: 9cc37344-4869-43d0-8008-72569c7a433d
    run.googleapis.com/urls: '["https://vdo-content-1040928076984.asia-southeast1.run.app"]'
    serving.knative.dev/creator: deployer@ecol-b0859.iam.gserviceaccount.com
    serving.knative.dev/lastModifier: sorranop@leanstructure.net
  creationTimestamp: '2026-02-18T06:44:59.863394Z'
  generation: 2
  labels:
    cloud.googleapis.com/location: asia-southeast1
    commit-sha: 94493c59748eafe2655b0061785966beb77be220
    managed-by: github-actions
    run.googleapis.com/satisfiesPzs: 'true'
  name: vdo-content
  namespace: '1040928076984'
  resourceVersion: AAZLE5/5MvA
  selfLink: /apis/serving.knative.dev/v1/namespaces/1040928076984/services/vdo-content
  uid: e20a0139-09ac-458c-852a-6b319ec9f5d2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 552.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: xrgafsthya
        commit-sha: 94493c59748eafe2655b0061785966beb77be220
        managed-by: github-actions
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: STREAMLIT_SERVER_HEADLESS
          value: 'true'
        - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
          value: 'false'
        - name: DEEPSEEK_API_KEY
          value: 'sk-2f8f48786320451197aac74a885a934e'
        image: asia-southeast1-docker.pkg.dev/ecol-b0859/vdo-content/app:94493c59748eafe2655b0061785966beb77be220
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 1040928076984-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  conditions:
  - lastTransitionTime: '2026-02-18T06:52:00.575977Z'
    message: "Revision 'vdo-content-00002-6ts' is not ready and cannot serve traffic.\
      \ spec.template.spec.containers[0].env[2].value_from.secret_key_ref.name: Permission\
      \ denied on secret: projects/1040928076984/secrets/DEEPSEEK_API_KEY/versions/latest\
      \ for Revision service account 1040928076984-compute@developer.gserviceaccount.com.\
      \ The service account used must be granted the 'Secret Manager Secret Accessor'\
      \ role (roles/secretmanager.secretAccessor) at the secret, project or higher\
      \ level."
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: Ready
  - lastTransitionTime: '2026-02-18T06:52:00.555088Z'
    message: "spec.template.spec.containers[0].env[2].value_from.secret_key_ref.name:\
      \ Permission denied on secret: projects/1040928076984/secrets/DEEPSEEK_API_KEY/versions/latest\
      \ for Revision service account 1040928076984-compute@developer.gserviceaccount.com.\
      \ The service account used must be granted the 'Secret Manager Secret Accessor'\
      \ role (roles/secretmanager.secretAccessor) at the secret, project or higher\
      \ level."
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: ConfigurationsReady
  - lastTransitionTime: '2026-02-18T06:52:00.575977Z'
    message: "Revision 'vdo-content-00002-6ts' is not ready and cannot serve traffic.\
      \ spec.template.spec.containers[0].env[2].value_from.secret_key_ref.name: Permission\
      \ denied on secret: projects/1040928076984/secrets/DEEPSEEK_API_KEY/versions/latest\
      \ for Revision service account 1040928076984-compute@developer.gserviceaccount.com.\
      \ The service account used must be granted the 'Secret Manager Secret Accessor'\
      \ role (roles/secretmanager.secretAccessor) at the secret, project or higher\
      \ level."
    reason: SecretsAccessCheckFailed
    status: 'False'
    type: RoutesReady
  latestCreatedRevisionName: vdo-content-00002-6ts
  observedGeneration: 2
